apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: web-server
  namespace: python-web-server
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - triggerRef: web-server-trigger